config/routes.rb
Ptaatlantis::Application.routes.draw do
  devise_for :admins

  concern :sortable do
    post :reorder, on: :collection
  end

  namespace :cms do
    resources :admins
    resources :mappins
    resources :activities
    resources :galleries do
      resources :gallery_images, concerns: :sortable
    end
  end

  root 'kuhsaft/pages#show'

  mount Kuhsaft::Engine => '/'

  get '(*url)' => 'kuhsaft/pages#show', :as => :page
end

app/models/activity.rb
require 'shoestrap/cms_model'

class Activity < ActiveRecord::Base
  include Shoestrap::CMSModel

  MEETING_POINTS = [
    '1 - Rosenau',
    '2 - Zinzikon',
    '3 - Bäumli',
    '4 - Waldheim',
    '5 - Lindspitz',
    '6 - Breiti',
    '7 - Oberseen',
    '8 - Bahnhof Seen',
    '9 - Schulhaus Dorf',
    '10 - Bettenplatz',
    '11 - Technikum'
  ]

  validates_presence_of :title, :starts_at

  scope :ordered, -> { order('starts_at ASC') }
  scope :from_now, -> { Activity.ordered.where("starts_at > ?", Date.today - 1.day) }

  editable_attributes :starts_at, :title, :description, :atlas, :titan, :artemis, :meeting_point
end

app/models/admin.rb
require 'shoestrap/cms_model'

class Admin < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable,
         :recoverable, :rememberable, :trackable, :validatable
  include Shoestrap::CMSModel

  # TODO: Define what attributes are shown in the form and permitted by strong parameters
  editable_attributes :first_name, :last_name, :email, :password

  # TODO: Define what attributes are shown in the index view
  index_attributes :first_name, :last_name, :email
end

app/models/gallery.rb
require 'shoestrap/cms_model'

class Gallery < ActiveRecord::Base
  include Shoestrap::CMSModel

  scope :ordered, -> { order(:position) }

  has_many :gallery_images

  validates_presence_of :title

  editable_attributes :title, :text
end

app/models/gallery_image.rb
require 'shoestrap/cms_model'

class GalleryImage < ActiveRecord::Base
  include Shoestrap::CMSModel
  belongs_to :gallery
  acts_as_list scope: :gallery

  default_scope -> { order('position ASC') }

  after_initialize :set_position

  has_attached_file :image,
    styles: { big: '980x735>', thumb: '160x120>' },
    :path => ":rails_root/public/system/:class/:attachment/:id/:style/:filename",
    :url => "/system/:class/:attachment/:id/:style/:filename"

  validates_attachment_content_type :image, :content_type => /\Aimage\/.*\Z/

  validates_presence_of :image, :gallery_id

  editable_attributes :image, :description, :gallery_id, :position

  private

  def set_position
    self.position ||= self.gallery.gallery_images.any? ? self.gallery.gallery_images.maximum(:position) + 1 : 1
  end
end

app/models/kuhsaft/activity_brick.rb
module Kuhsaft
  class ActivityBrick < Brick

    def collect_fulltext
      [super, caption].join(' ')
    end

    def user_can_add_childs?
      false
    end
  end
end

app/models/kuhsaft/gallery_brick.rb
module Kuhsaft
  class GalleryBrick < Brick

    validates_presence_of :gallery_id

    def collect_fulltext
      [super, caption].join(' ')
    end

    def user_can_add_childs?
      false
    end
  end
end

app/models/kuhsaft/image_brick.rb
module Kuhsaft
  class ImageBrick < Brick

    has_attached_file :image,
      styles: { big: '1000x800>', thumb: '120x100>' },
      :path => ":rails_root/public/system/:class/:attachment/:id/:style/:filename",
      :url => "/system/:class/:attachment/:id/:style/:filename"

    validates :image, :presence => true
    validates_attachment :image, content_type: { content_type: ["image/jpg", "image/jpeg", "image/png"] }

    def collect_fulltext
      [super, caption].join(' ')
    end

    def user_can_add_childs?
      false
    end
  end
end

app/models/kuhsaft/map_brick.rb
module Kuhsaft
  class MapBrick < Brick

    def collect_fulltext
      [super, caption].join(' ')
    end

    def user_can_add_childs?
      false
    end
  end
end

app/models/mappin.rb
require 'shoestrap/cms_model'

class Mappin < ActiveRecord::Base
  include Shoestrap::CMSModel

  after_save :touch_map_bricks

  validates_presence_of :lat, :lng, :marker_text

  editable_attributes :lat, :lng, :marker_text

  index_attributes :lat, :lng, :marker_text

  def self.pin_array
    pin_array = []
    self.all.each do |p|
      pin_array << p.marker_text
    end
    pin_array
  end

  def touch_map_bricks
    Kuhsaft::Brick.where(type: 'Kuhsaft::MapBrick').each do |map_brick|
      map_brick.touch
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
  helper Kuhsaft::Engine.helpers
  after_action :flash_to_headers

  protected

  def flash_to_headers
    return unless request.xhr?
    [:error, :warning, :notice, :success].each do |type|
      next if flash[type].blank?
      response.headers['X-Message'] = flash[type]
      response.headers['X-Message-Type'] = type.to_s
    end
    flash.discard # don't want the flash to appear when you reload page
  end
end

app/controllers/cms/activities_controller.rb
class Cms::ActivitiesController < Shoestrap::BaseController

  private

  def collection
    Activity.ordered
  end
end

app/controllers/cms/admins_controller.rb
module Cms
  class AdminsController < Shoestrap::BaseController
  end
end

app/controllers/cms/galleries_controller.rb
class Cms::GalleriesController < Shoestrap::BaseController

  private

  def collection
    Gallery.ordered
  end
end

app/controllers/cms/gallery_images_controller.rb
class Cms::GalleryImagesController < Shoestrap::BaseController

  def new
    @gallery_image = GalleryImage.new(gallery_id: params[:gallery_id])
  end

  def create
    create!{ cms_gallery_gallery_images_path(resource.gallery) }
  end

  def update
    update!{ cms_gallery_gallery_images_path(resource.gallery) }
  end

  def destroy
    destroy!{ cms_gallery_gallery_images_path(resource.gallery) }
  end

  def reorder
    GalleryImage.find(params[:gallery_image][:id]).insert_at(params[:gallery_image][:position].to_i)
    redirect_to cms_gallery_gallery_images_path(resource.gallery)
  end
end

app/controllers/cms/mappins_controller.rb
class Cms::MappinsController < Shoestrap::BaseController
end

app/controllers/shoestrap/base_controller.rb
module Shoestrap
  class BaseController < Kuhsaft::Cms::AdminController
    inherit_resources

    before_action :authenticate_admin!

    def show
      super do |format|
        format.html { redirect_to collection_path }
      end
    end

    private

    def permitted_params
      params.permit(resource_instance_name => collection.editable_attributes)
    end
  end
end

app/controllers/styleguide_controller.rb
class StyleguideController < ApplicationController
  def basestyles; end
end

app/helpers/application_helper.rb
module ApplicationHelper
  def body_class
    "controller-#{controller_name} action-#{action_name}"
  end

  def google_analytics_code
    return if ENV['GOOGLE_ANALYTICS_CODE'].blank? || !Rails.env.production?
    render 'partials/google_analytics', google_analytics_code: ENV['GOOGLE_ANALYTICS_CODE']
  end
end

app/views/cms/activities/_form.html.haml
%hr
= simple_form_for([:cms, resource], wrapper: :bootstrap, html: { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    = f.input :starts_at
    = f.input :title
    = f.input :description
    = f.input :atlas
    = f.input :titan
    = f.input :artemis
    = f.input :meeting_point, collection: Activity::MEETING_POINTS + Mappin.pin_array

  .form-actions
    = f.button :submit

app/views/cms/activities/index.html.haml
%h1= t("cms.index_title", plural_name: t("cms.#{resource_collection_name}.plural_name"))

.row-fluid.actions
  .pull-right.padded
    = link_to new_resource_path, :class => 'btn btn-primary' do
      %i.icon-plus-sign.icon-white
      = t("cms.#{resource_collection_name}.new", plural_name: resource_collection_name, default: t('cms.default.new'))

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th= collection.human_attribute_name :starts_at
      %th= collection.human_attribute_name :title
      %th= collection.human_attribute_name :description
      %th= collection.human_attribute_name :atlas
      %th= collection.human_attribute_name :titan
      %th= collection.human_attribute_name :artemis
      %th= collection.human_attribute_name :meeting_point
      %th
      %th

  %tbody
    - collection.each do |item|
      %tr
        %td= item.starts_at.strftime('%d.%m - %H:%M Uhr')
        %td= item.title
        %td= item.description
        %td
          %i{ class: item.atlas ? 'icon-ok' : 'icon-remove' }
        %td
          %i{ class: item.titan ? 'icon-ok' : 'icon-remove' }
        %td
          %i{ class: item.artemis ? 'icon-ok' : 'icon-remove' }
        %td= item.meeting_point
        %td= link_to t("cms.edit"), edit_resource_path(item)
        %td
          =link_to resource_path(item), method: :delete, data: { confirm: t('cms.are_you_sure') }, class: 'btn btn-small btn-danger' do
            %i.icon-trash.icon-white
            =t('cms.destroy')

%br

app/views/cms/galleries/index.html.haml
%h1= t("cms.index_title", plural_name: t("cms.#{resource_collection_name}.plural_name"))

.row-fluid.actions
  .pull-right.padded
    = link_to new_resource_path, :class => 'btn btn-primary' do
      %i.icon-plus-sign.icon-white
      = t("cms.#{resource_collection_name}.new", plural_name: resource_collection_name, default: t('cms.default.new'))

%table.table.table-bordered.table-striped
  %thead
    %tr
      %th= collection.human_attribute_name :title
      %th= collection.human_attribute_name :text
      %th Bilder
      %th

  %tbody
    - collection.each do |item|
      %tr
        %td= item.title
        %td= item.text
        %td
          = link_to new_cms_gallery_gallery_image_path(item), class: 'btn btn-primary btn-small btn-block' do
            %i.icon-plus-sign.icon-white
          = link_to cms_gallery_gallery_images_path(item), class: 'btn btn-small btn-block' do
            %i.icon-th-list
            = "(#{item.gallery_images.count})"
        %td
          = link_to edit_resource_path(item), class: 'btn btn-small' do
            %i.icon-edit
            = t("cms.edit")
          =link_to resource_path(item), method: :delete, data: { confirm: t('cms.are_you_sure') }, class: 'btn btn-small btn-danger' do
            %i.icon-trash.icon-white
            =t('cms.destroy')

%br

app/views/cms/mappins/index.html.haml
%h1= t("cms.index_title", plural_name: t("cms.#{resource_collection_name}.plural_name"))

.row-fluid.actions
  .pull-right.padded
    = link_to new_resource_path, :class => 'btn btn-primary' do
      %i.icon-plus-sign.icon-white
      = t("cms.#{resource_collection_name}.new", plural_name: resource_collection_name, default: t('cms.default.new'))

%table.table.table-bordered.table-striped
  %thead
    %tr
      - collection.index_attributes.each do |column_name|
        %th= collection.human_attribute_name column_name
      %th
      %th

  %tbody
    - collection.each do |item|
      %tr
        - collection.index_attributes.each do |column_name|
          %td= item.send(column_name)
        %td= link_to t("cms.edit"), edit_resource_path(item)
        %td
          =link_to resource_path(item), method: :delete, data: { confirm: t('cms.are_you_sure') }, class: 'btn btn-small btn-danger' do
            %i.icon-trash.icon-white
            =t('cms.destroy')

%br

%h3 Hilfe zu Längen-/Breitengrad
= image_tag 'map_expl.png'
%br
%br
%p In Google Maps auf die Karte klicken, um die entsprechenden Werte angezeigt zu bekommen
%p Breitengrade müssten um ~47.x sein, Längengrade bei ~8.x

app/views/kuhsaft/gallery_bricks/gallery_brick/_edit.html.haml
= form.input :gallery_id, collection: Gallery.ordered, label_method: lambda { |g| g.title }

app/views/kuhsaft/image_bricks/_image_brick.html.haml
.row{ :class => image_brick.to_style_class }
  .columns.text-center
    - if image_brick.image.present?
      = image_tag(image_brick.image.url(:big), alt: image_brick.alt_text.present? ? image_brick.alt_text : image_alt(image_brick.image.path) )

      - if image_brick.caption.present?
        .image-caption.text-left
          = image_brick.caption

app/views/kuhsaft/image_bricks/image_brick/_edit.html.haml
- if brick.image.present?
  .control-group
    %label.control-label= t('.image_preview')
    .controls
      = link_to brick.image(:big) do
        = image_tag brick.image(:thumb)

= form.file_field :image
= form.input :alt_text, :as => :string, :input_html => { :class => 'span6' }
= form.input :caption, :as => :string, :input_html => { :class => 'span6' }

app/views/kuhsaft/map_bricks/_map_brick.html.haml
%script{ src: "//maps.google.com/maps/api/js?v=3.13&amp;sensor=false&amp;libraries=geometry", type: "text/javascript" }
%script{ src: '//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js', type: 'text/javascript' }
%script{ src: '//google-maps-utility-library-v3.googlecode.com/svn/trunk/richmarker/src/richmarker-compiled.js', type: 'text/javascript' }

.row{ :class => map_brick.to_style_class }
  .columns.small-12
    .map-container
      #map

:coffee
  window.mrkrs = []

- Mappin.all.each do |pin|
  :coffee
    window.mrkrs.push(
      {
        lat: "#{pin.lat}"
        lng: "#{pin.lng}"
        custom_marker: "#{pin.marker_text}"
      }
    )


:coffee
  class CustomMarkerBuilder extends Gmaps.Google.Builders.Marker
    create_marker: ->
      options = _.extend @marker_options(), @rich_marker_options()
      @serviceObject = new RichMarker options

    rich_marker_options: ->
      marker = document.createElement("div")
      marker.setAttribute('class', 'custom_marker')
      marker.innerHTML = this.args.custom_marker
      { content: marker }

    create_infowindow: ->
      return null unless _.isString @args.custom_infowindow

      boxText = document.createElement("div")
      boxText.setAttribute("class", 'custom_infowindow_content')
      boxText.innerHTML = @args.custom_infowindow
      @infowindow = new InfoBox(@infobox(boxText))

    infobox: (boxText)->
      content: boxText
      pixelOffset: new google.maps.Size(-140, 0)
      boxStyle:
        width: "280px"

  dem_markers = [
    {
      lat: 47.5
      lng: 8.7
      custom_marker: 'dynamic'
      html_string: 'someclass'
    }
  ]


  handler = Gmaps.build('Google', builders: { Marker: CustomMarkerBuilder } )
  handler.buildMap {
    provider: {}
    internal: id: 'map'
  }, ->
    markers = handler.addMarkers(window.mrkrs)
    handler.bounds.extendWith markers
    handler.fitMapToBounds()
    return

app/views/kuhsaft/text_bricks/_text_brick.html.haml
.row{ :class => text_brick.to_style_class }
  .columns.large-10.large-offset-1
    = text_brick.text.to_s.html_safe

app/views/kuhsaft/video_bricks/video_brick/_edit.html.haml
.alert.alert-info
  %p "Embed Code" von youtube (iframe) verwenden und dabei die 'width' und 'height' attribute löschen.
  %br
  %p Beispiel:
  %code
    = '<iframe src="//www.youtube.com/embed/8MVQvyEXHTY" frameborder="0" allowfullscreen></iframe>'
= form.input :embed_src, :as => :text, :input_html => { :class => 'span6', :rows => 5 }

app/views/shoestrap/base/_form.html.haml
%hr
= simple_form_for([:cms, resource], wrapper: :bootstrap, html: { class: 'form-horizontal' }) do |f|
  = f.error_notification

  .form-inputs
    - resource.class.editable_attributes.each do |column_name|
      - if column_name.to_s.end_with? '_id'
        = f.association column_name.to_s.gsub(/_id$/, '').to_sym
      - else
        = f.input column_name

  .form-actions
    = f.button :submit

app/views/shoestrap/base/edit.html.haml
%h1= t("cms.edit_title", singular_name: t("cms.#{resource_collection_name}.singular_name"))

= render 'form'

= link_to t('cms.back'), collection_path

app/views/shoestrap/base/index.html.haml
%h1= t("cms.index_title", plural_name: t("cms.#{resource_collection_name}.plural_name"))

.row-fluid.actions
  .pull-right.padded
    = link_to new_resource_path, :class => 'btn btn-primary' do
      %i.icon-plus-sign.icon-white
      = t("cms.#{resource_collection_name}.new", plural_name: resource_collection_name, default: t('cms.default.new'))

%table.table.table-bordered.table-striped
  %thead
    %tr
      - collection.index_attributes.each do |column_name|
        %th= collection.human_attribute_name column_name
      %th
      %th

  %tbody
    - collection.each do |item|
      %tr
        - collection.index_attributes.each do |column_name|
          %td= item.send(column_name)
        %td= link_to t("cms.edit"), edit_resource_path(item)
        %td
          =link_to resource_path(item), method: :delete, data: { confirm: t('cms.are_you_sure') }, class: 'btn btn-small btn-danger' do
            %i.icon-trash.icon-white
            =t('cms.destroy')

%br

app/views/shoestrap/base/new.html.haml
%h1= t("cms.new_title", singular_name: t("cms.#{resource_collection_name}.singular_name"))

= render 'form'

= link_to t('cms.back'), collection_path